# Generated by Django 4.1.7 on 2023-04-05 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_student_id_issuedbook_subscriber_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 5, 17, 49, 15, 727143)),
        ),
    ]
