# Generated by Django 4.1.7 on 2023-04-05 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_issuedbook_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 5, 22, 43, 16, 722814)),
        ),
    ]
