# Generated by Django 4.1.7 on 2023-04-06 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_subscriber_id_issuedbook_subscriber_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 6, 19, 21, 58, 544691)),
        ),
    ]
