# Generated by Django 4.1.7 on 2023-04-08 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_issuedbook_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entry_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 8, 14, 19, 13, 872036)),
        ),
    ]
