# Generated by Django 4.1.7 on 2023-04-08 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_entry_check_alter_issuedbook_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='entry_check',
            new_name='check_administrator',
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 8, 14, 21, 47, 243840)),
        ),
    ]
