# Generated by Django 4.1.7 on 2023-04-22 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_issuedbook_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 10, 31, 30, 658501)),
        ),
    ]
