# Generated by Django 4.1.7 on 2023-04-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_book_cover_alter_issuedbook_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedbook',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 17, 36, 48, 312579)),
        ),
    ]
